// apps/grid-angular/projects/grid-angular/src/lib/grid/components/loading-indicator/grid-loading-indicator.ts
import { ChangeDetectionStrategy, Component } from '@angular/core';
import { MozLoaderComponent } from '@mozaic-ds/angular';

@Component({
  selector: 'ad-grid-loading-indicator',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [MozLoaderComponent],
  template: `
    <div class="grid-loading-indicator">
      <moz-loader size="s" text="Loading more data..." />
    </div>
  `,
  styles: [
    `
      .grid-loading-indicator {
        display: flex;
        align-items: center;
        justify-content: center;
        padding: var(--spacing-m, 16px);
        border-top: 1px solid var(--color-border-primary);
        background: var(--color-background-primary);
      }
    `,
  ],
})
export class AdeoGridLoadingIndicatorComponent {}

// apps/grid-vue/src/components/Grid/components/footer/GridLoadingIndicator.vue
<script setup lang="ts">
/**
 * Loading indicator — Angular parity (`moz-grid-loading-indicator`).
 *
 * Thin leaf component displayed below the grid body while the async loading
 * strategy is fetching more rows. Mirrors the Angular `<moz-grid-loading-indicator>`:
 * a small Mozaic `MLoader` with an optional text label, sitting on top of a
 * separator to visually detach it from the last rendered row.
 */

import { MLoader } from '@mozaic-ds/vue'

withDefaults(
  defineProps<{
    /** Label next to the spinner. Defaults to "Loading more data…" for parity. */
    text?: string
    /** Loader size — passed through to `MLoader`. */
    size?: 'xs' | 's' | 'm' | 'l'
  }>(),
  {
    text: 'Loading more data...',
    size: 's',
  },
)
</script>

<template>
  <div class="adeo-grid-grid-loading-indicator">
    <MLoader :size="size" :text="text" />
  </div>
</template>

<style scoped lang="scss">
.adeo-grid-grid-loading-indicator {
  display: flex;
  align-items: center;
  justify-content: center;
  padding: m.get-spacing('200');
  border-top: m.get-token('border-width', 's') solid var(--color-border-primary);
  background: var(--color-background-primary);
}
</style>
